services:
  ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://melodex:%25aZm%401%23stCpRHD%21vLUvnBYiA@db:5432/melodex?schema=public
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      SMTP_SERVER_USERNAME: ${SMTP_SERVER_USERNAME}
      SMTP_SERVER_PASSWORD: ${SMTP_SERVER_PASSWORD}
      SMTP_SERVER_HOST: ${SMTP_SERVER_HOST}
      SMTP_SERVER_PORT: ${SMTP_SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: melodex
      POSTGRES_PASSWORD: "%aZm@1#stCpRHD!vLUvnBYiA"
      POSTGRES_DB: melodex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U melodex -d melodex"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: